dakshsinghrathore/Brighter-Beginnings

- dist/style.css
#3 
solved the glitch in responsivness for all devices
> responsiveness fltich solved

- dist/logic.html
issue #26 
added a line of information about the games in the logic page.
> Added description to webpage.

- dist/logic.html
fixes #34 
Now image for sudoku solver is clickable
> Anchor tag updated and image is now clickable

- dist/register.html
- dist/style.css
Fixed: #18 
I've redesigned the register page while keeping the root elements as it is
> Feat: Improved the register page

- dist/index.html
fixed #48 
I've incorporated graphics and new background which makes it look more lively.
**The lag in this recording is due to my low system configuration and due to that it was lagging when i turned on the recorder but ideally the animation of page doesnot stutter and is smooth.**
https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/134225415/c4b72e77-5b13-408f-920c-264a00ac0532
> feat :Enhanced Home page

- dist/index.html
- dist/style.css
Issue #37 fixed. Now Navbar in mobile view does not overlaps with Login and Register button.
Navbar in mobile now does not overlap with Buttons and also on changing screen size Navbar in mobile view closes.
> Issue #37 Navbar in mobile is fixed.

- dist/development.html
Closes #52 
Added three more courses from youtube.
> feat: added more courses in m3

- dist/register.css
- dist/register.html
Fixed #69 
FIxed the background issue
> fixed: registeration page background

- dist/register.html
- issue #79 
- Enhance user engagement and promote inclusivity on the website with this latest feature update – a captivating tagline for the registration page.
> Updated register.html

- dist/index.html
issue #87 
Fixed the issue where the menu button when pressed for the first time did not open the header menu.
> fix: menu button does not work on first click

- dist/development.html
Issue no #63 
I have fixed the issue where the button was not visible in some pages
> Fixed button visibility in development.html

- dist/logic.html
closes #95 
Added games like brain test tricky
> image changes

- dist/index.html
completes issue #14
provides a team page interface already created by github, as dynamic fetch using github action was not feasible.
> anchored our teams with github contributors page

- dist/index.html
solves issue #59 
Added Google form link as anchor
https://forms.gle/iSwLAuT7ZwjaqpY97
> Student Contribution Portal Form

- dist/logic.html
- dist/script.js
- dist/style.css
> Added dropdown effect to profile picture

- dist/development.html
The Let's Get Started button is aligned with complete responsiveness as per other courses' page
Before : 
After :
> let's get started button in development page aligned as per other courses' page

- dist/style.css
issue #111 solved
Added hovering effect for images in Get started page
https://github.com/dakshsinghrathore/Brighter-Beginnings/assets/120392487/ff3564f3-5a71-4932-b639-a17e2ae23352
> Added hovering effect in Get started page

- dist/logic.html
Issue#112
added free the key game
> Added free the key game

- dist/about.html
- dist/development.html
- dist/logic.html
- dist/problemsolving.html
Issue #132 
Changed all footer bg color to neural white and also changed the color of the about page body to match the footer
about page
logic page
> git commit -m "fix: color discrepancy"

- dist/getstarted.html
#127 
I have added icons on Home and Feedback button
> Added icons on Home and Feedback button

- .vscode/settings.json
- dist/register.css
- dist/register.html
IssueNo:#134
I have added validations to all the fields present in the registration page.I have also ensured both the passwords are matching.I have also enforced strong password matching using regex.Only passwords with atleast 8 characters containing atleast one letter ,one number and one special character will be accepted.I have also added eye icon for password visibility.
> feat:Added validations to all the fields present in the Registration page.

- dist/problemsolving.html
closes #114 
Added kwargs and args of python to problem solving page
> Added kwargs and args of python to problem solving page

- dist/problemsolving.html
> Fixed Typo errors

- dist/about.html
- dist/feedback.html
This PR enhances the newsletter subscription feature by incorporating validations and adding a confirmation popup. Users will now experience improved feedback and receive a confirmation message after subscribing to the newsletter.
IssueNo:#136
1. **Newsletter Validations:**
- Implemented client-side validations for the newsletter subscription form to ensure users enter valid information.
- Added checks for email format and required fields.
2. **Confirmation Popup:**
- Introduced a confirmation popup to notify users that they have successfully subscribed to the newsletter.
- Enhanced the popup styling to provide a visually pleasing and user-friendly experience. Additionally, implemented functionality for the popup to close when the user clicks on the greyed-out screen, which appears when …
> feat:Added Validations to the Newsletter and Confirmation Popup

- dist/index.html
1. Nav tag
- changed the hover style of the 'About', 'Services', 'Blog' links for better consistency
2. footer
- changed the hover style of the 'About' link for better consistency
- **Nav tag:** the style of the 'About', 'Services', 'Blog' non-button links were very underwhelming and felt a little out. So the hover color has been changed to blue so that they feel more alive and not dull. the color blue was chosen so that the overall style still fits perfectly well with the whole page and they don't pop out too much
- **Footer:** the style of the 'About' link which redirects to the About.html page was inconsistent when compared to other links. This PR fixes that issue and makes the link style consistent with the other links.
> Improved styling of Nav and footer tag links 

- dist/register.css
- dist/register.html
closes #140 
Added a glassmorphic effect to the register page for improved text clarity
> Added glassmorphic effect in register page

- dist/index.html
**Related Issue:**
This PR resolves the issue #141 
**Description:**
The current hero section background in the homepage appears plain and lacks visual appeal. This pull request aims to improve the aesthetics by adding a gradient background, enhancing the overall look and feel of the hero section.
**Proposed Changes:**
Introduce a gradient background for the hero section, providing a visually appealing and dynamic backdrop. This enhancement aims to create a more engaging user experience.
**Expected Outcome:**
Users will notice an improved visual appeal in the hero section with the addition of a gradient background. The overall aesthetics of the homepage will be enhanced.
**Screenshots**
@dakshsinghrathore please review this PR and don't forget to add SWOC and difficulty level label to the …
> style: enhance hero section background

- .github/dependabot.yml
Fixes #148  
This Pull Request addresses the need to automate the management of project dependencies for enhanced stability, security, and maintenance.
1. **Dependabot Integration:** Add Dependabot to the project.
2. **Automated Dependency Updates:** Upon activation, Dependabot will automatically submit pull requests (PRs) when outdated dependencies are identified in our `package.json` file.
- **Stability:** Ensures the project remains stable by adopting the latest versions of dependencies.
- **Security:** Enhances security by promptly addressing and updating vulnerable dependencies.
- **Maintenance:** Automates the process, reducing manual effort and ensuring continuous improvement.
@dakshsinghrathore please review this PR.
Thanks
> feat: add dependabot for dependency updates

- dist/index.html
- dist/ourteam.html
Closes #14 
Its a page for displaying the GitHub repo contributors as our team.
> Created Our Team page

- dist/about.html
- dist/index.html
#139 
Added the suitable icons on the navbar
> Added icons

- .github/auto_assign.yml
- .github/workflows/action.yml
This PR closes issue #164 
This pull request addresses the need for a GitHub Actions workflow that automates the process of assigning reviewers to pull requests upon their opening. By implementing this feature, we aim to streamline our code review processes and ensure timely feedback from team members.
- `.github/workflows/action.yml`
- `.github/auto_assign.yml`
1. **Workflow Development:** Introduce a GitHub Actions workflow script that triggers upon the opening of a pull request.
2. **Reviewer Assignment Logic:** Implement logic to automatically assign reviewers based on predefined rules or configurations defined in the workflow config.
- The workflow triggers automatically when a pull request is opened.
- Reviewers are assigned to the pull request based on the defined rules or …
> feat: Implement reviewer assignment workflow

- .github/.labeler.yml
- .github/workflows/labeler.yml
> feat: labeler automation

- .github/workflows/labeler.yml
> feat: labeler automation added v1

- .github/workflows/labeler.yml
> feat: labeler automation added v3

- .github/workflows/labeler.yml
> feat: labeler automation added v4

- .github/workflows/labeler.yml
> feat: labeler automation added v6
